Adding columns to a DataFrame

In [25]:
import numpy as np
import pandas as pd

In [26]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

df = pd.DataFrame(data)

In [27]:
print('DataFrame before New column')
df.head()

DataFrame before New column

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [28]:
address = ['NYC','NJ','CA','PA']
df['Address'] = address

In [29]:
print('Data frame after')
df.head()

Data frame after

     Name  Height Qualification  Score 1  Score 2 Address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

Creatind a New column using an old column(s)

In [30]:
df['Total_Score'] = df['Score 1'] +df['Score 2']
print("after column added")
df.head()

after column added

     Name  Height Qualification  Score 1  Score 2 Address  Total_Score
0    Jane     5.1           Msc       56       50     NYC          106
1  Princi     6.2            MA       86       96      NJ          182
2   James     5.1           Msc       77       60      CA          137
3    Fadi     5.2           Msc       45       30      PA           75

In [31]:
df['avg_Score'] = (df['Total_Score'])/2
print("after column added")
df.head()

after column added

,Name,Height,Qualification,Score 1,Score 2,Address,Total_Score,avg_Score
0,Jane,5.1,Msc,56,50,NYC,106,53.0
1,Princi,6.2,MA,86,96,NJ,182,91.0
2,James,5.1,Msc,77,60,CA,137,68.5
3,Fadi,5.2,Msc,45,30,PA,75,37.5

Importing specified columns and rearranging them

In [32]:
df2 = pd.DataFrame(data,columns= ['Score 1','Score 2','Name','Qualification'])

print(df2)

   Score 1  Score 2    Name Qualification
0       56       50    Jane           Msc
1       86       96  Princi            MA
2       77       60   James           Msc
3       45       30    Fadi           Msc

In [33]:
values = [['Rohan', 455], ['Elvish', 250], ['John', 495],
          ['Sai', 400], ['Eric', 350], ['Adam', 450]]
df3 = pd.DataFrame(values,columns=['Name','Univ_Marks'])
df3.head()

     Name  Univ_Marks
0   Rohan         455
1  Elvish         250
2    John         495
3     Sai         400
4    Eric         350

In [34]:
df3['Percentage'] =(df3['Univ_Marks'] /500) * 100
df3.head()

     Name  Univ_Marks  Percentage
0   Rohan         455        91.0
1  Elvish         250        50.0
2    John         495        99.0
3     Sai         400        80.0
4    Eric         350        70.0

## Using the insert method to add a column

In [36]:
df3.insert(1,'Age',[1000,2000,50,60,12,13])
df3.head()

     Name   Age  Univ_Marks  Percentage
0   Rohan  1000         455        91.0
1  Elvish  2000         250        50.0
2    John    50         495        99.0
3     Sai    60         400        80.0
4    Eric    12         350        70.0

In [38]:
df3 =df3.assign(location =('middleeast','land','Nyc','NJ','CA','NC'))
df3.head()

     Name   Age  Univ_Marks  Percentage    location
0   Rohan  1000         455        91.0  middleeast
1  Elvish  2000         250        50.0        land
2    John    50         495        99.0         Nyc
3     Sai    60         400        80.0          NJ
4    Eric    12         350        70.0          CA