## handling missing values
- 'df.isnull()' - to detect missing values (same as df.isna())
- 'df.fillna()' - to fill missing values
-df.dropna() -to remove missing values
- df.replace - to replace or impute the values(Imputation)

In [2]:
import pandas as pd
import numpy as np

In [12]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]

emp_df = pd.DataFrame(employee_list,columns =['Name','Age','weight','Salary'])
emp_df.head(10)

       Name   Age  weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN

In [4]:
rows,cols =emp_df.shape
print('rows',rows ,'Column',cols)

rows 14 Column 4

In [7]:
emp_df.isnull().sum()

Name      1
Age       3
weight    1
Salary    2
dtype: int64

# Be wary of missing values,if u hav small dataset ,removing values can alter analysis
# missing data rows is less than 2.5 % of data set is safe.
# when dropping na, you remove the entire row

In [9]:
dropped_df = emp_df.dropna()
print(dropped_df)

        Name   Age  weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
13      John  41.0    85.0  1528000.0

In [10]:
filled_df =emp_df.fillna('None')
print(filled_df)

        Name   Age weight     Salary
0      James  36.0   75.0  5428000.0
1    Villers  38.0   74.0  3428000.0
2      VKole  31.0   70.0  8428000.0
3      Smith  34.0   80.0  4428000.0
4      Gayle  40.0  100.0  4528000.0
5       Adam  40.0   None  4528000.0
6     Rooter  33.0   72.0  7028000.0
7   Peterson  42.0   85.0  2528000.0
8      lynda  42.0   85.0       None
9       None  42.0   85.0       None
10     Jenny  None  100.0    25632.0
11      Kenn  None  110.0    25632.0
12       Aly  None   90.0    25582.0
13      John  41.0   85.0  1528000.0

In [11]:
filled_df.isnull().sum()

Name      0
Age       0
weight    0
Salary    0
dtype: int64

In [14]:
# only change values of certain columns
specific_cols = emp_df[['weight','Age']].fillna('pending')
specific_cols

     weight      Age
0      75.0     36.0
1      74.0     38.0
2      70.0     31.0
3      80.0     34.0
4     100.0     40.0
5   pending     40.0
6      72.0     33.0
7      85.0     42.0
8      85.0     42.0
9      85.0     42.0
10    100.0  pending
11    110.0  pending
12     90.0  pending
13     85.0     41.0

In [15]:
emp_df2 = emp_df.fillna(value ={'weight':'pending','Age':'unknown','Salary':'0.0','Name':'verification pending'})
emp_df2

                    Name      Age   weight     Salary
0                  James     36.0     75.0  5428000.0
1                Villers     38.0     74.0  3428000.0
2                  VKole     31.0     70.0  8428000.0
3                  Smith     34.0     80.0  4428000.0
4                  Gayle     40.0    100.0  4528000.0
5                   Adam     40.0  pending  4528000.0
6                 Rooter     33.0     72.0  7028000.0
7               Peterson     42.0     85.0  2528000.0
8                  lynda     42.0     85.0        0.0
9   verification pending     42.0     85.0        0.0
10                 Jenny  unknown    100.0    25632.0
11                  Kenn  unknown    110.0    25632.0
12                   Aly  unknown     90.0    25582.0
13                  John     41.0     85.0  1528000.0

In [17]:
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }

tech_df = pd.DataFrame(technologies)
tech_df.head(10)

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [18]:
rows,cols= tech_df.shape
print('rows',rows ,'Column',cols)

rows 7 Column 4

In [19]:
tech_df.isnull().sum()

Courses     2
Fee         2
Duration    2
Discount    3
dtype: int64

In [20]:
tech1_df =tech_df.replace(np.nan,'')
tech1_df

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [24]:
tech3= tech_df.replace({'Courses':np.nan,'Fee':np.nan},'Pending')
tech3

   Courses      Fee Duration  Discount
0    Spark  20000.0      NaN    1000.0
1  Pending  25000.0   40days       NaN
2   Hadoop  Pending   35days    1500.0
3   Python  22000.0      NaN       NaN
4   pandas  24000.0   60days    2500.0
5  Pending  Pending   50days    2100.0
6     Java  22000.0   55days       NaN

In [ ]:
tech_df.fillna('')
tech_df

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [28]:
emp_df=pd.read_csv('data/employee.csv')
emp_df

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

In [29]:
emp_df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [31]:
emp1_df = emp_df.fillna(value=({'Name':'Pending verification','Age':'unknown','Weight':'pending','Salary':'0.0'}))
emp1_df

                    Name      Age   Weight     Salary
0                  James     36.0     75.0  5428000.0
1                Villers     38.0     74.0  3428000.0
2                  VKole     31.0     70.0  8428000.0
3                  Smith     34.0     80.0  4428000.0
4                  Gayle     40.0    100.0  4528000.0
5                   Adam     40.0  pending  4528000.0
6                 Rooter     33.0     72.0  7028000.0
7               Peterson     42.0     85.0  2528000.0
8                  lynda     42.0     85.0        0.0
9   Pending verification     42.0     85.0        0.0
10                 Jenny  unknown    100.0    25632.0
11                  Kenn  unknown    110.0    25632.0
12                   Aly  unknown     90.0    25582.0
13                  John     41.0     85.0  1528000.0
14                   Ali     26.0     69.0        0.0